server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalogs
        - id: seriesRoute
          uri: lb://series-service
          predicates:
            - Path=/series/**
          filters:
            - name: CircuitBreaker
              args:
                name: seriesService
                fallbackUri: forward:/fallback/series

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
        
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
