server:
  port: 8084

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: final_backend_db
      port: 27017
      host: mongodb

resilience4j:
  circuitbreaker:
    instances:
      catalog:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false

management:
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog service
